spring.application.name=url-shortener
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=Jvmp#0786
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect =org.hibernate.dialect.MySQLDialect




jwt.secret =6409f68474dd4523beb75e0ed3e77344b3c35bbad566db7bd78dee81a418c17b;
jwt.expiration=172800000


logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG
